import type { Metadata } from 'next'
import './globals.scss'

import Navbar from './components/navbar'

import { Suse, SpaceGrotesk } from './fonts/fonts'
import Footer from './components/footer'

export const metadata: Metadata = {
  title: '@Bavuett',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Suse.variable + " " + SpaceGrotesk.variable}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
